# Generated by Django 4.2.5 on 2023-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_sregmodelview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sregmodelview',
            name='imgup',
            field=models.FileField(default=1, upload_to='ecommerceapp/static'),
            preserve_default=False,
        ),
    ]
