# Generated by Django 4.2.5 on 2023-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_sregmodelview_imgup'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.FileField(upload_to='ecommerce/static')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('pdes', models.CharField(max_length=50)),
            ],
        ),
    ]
