# Generated by Django 4.2.5 on 2023-09-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_buyerregmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemup',
            name='category',
            field=models.CharField(choices=[('coffee', 'coffee'), ('cpowders', 'cpowders'), ('cmugs', 'cmugs'), ('camchines', 'cmachines'), ('cblenders', 'cblenders')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
