# Generated by Django 4.2.5 on 2023-09-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_itemup_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(upload_to='')),
                ('userid', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField()),
                ('prod_description', models.CharField(max_length=50)),
                ('prod_category', models.CharField(max_length=50)),
            ],
        ),
    ]
