# Generated by Django 4.2.5 on 2023-09-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='prod_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
