# Generated by Django 4.2.5 on 2023-09-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_wishlist_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimage', models.FileField(upload_to='')),
                ('kuserid', models.IntegerField()),
                ('kprod_id', models.IntegerField()),
                ('kprodname', models.CharField(max_length=30)),
                ('kprodprice', models.IntegerField()),
                ('kproddes', models.CharField(max_length=30)),
                ('kprodcat', models.CharField(max_length=30)),
            ],
        ),
    ]
