# Generated by Django 4.2.5 on 2023-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('delivery_add', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('streetname', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
