# Generated by Django 4.2.5 on 2023-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_delivery_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='country',
            field=models.CharField(choices=[('Kerala', 'Kerala')], max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Tamilnadu', 'Tamilnadu'), ('Karnataka', 'Karnataka')], max_length=50),
        ),
    ]
