# Generated by Django 4.2.5 on 2024-02-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0017_clregmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='lname',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='country',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('UnitedState', 'UnitedState'), ('Canada', 'Canada')], max_length=50),
        ),
    ]
