# Generated by Django 4.2.5 on 2024-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0019_cart_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_details',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
