# Generated by Django 4.2.5 on 2024-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0022_cardmodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.CharField(max_length=100)),
                ('prod_name', models.CharField(max_length=50)),
                ('booked_date', models.DateField()),
                ('amount', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
            ],
        ),
    ]
