# Generated by Django 4.2.5 on 2024-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0024_place_order_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_order',
            name='booked_date',
            field=models.CharField(max_length=50),
        ),
    ]
