# Generated by Django 4.2.5 on 2024-02-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0025_alter_place_order_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_order',
            name='prod_img',
        ),
    ]
