# Generated by Django 4.2.5 on 2024-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0027_rename_zip_cart_details_pin_cart_details_prod_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='booking_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='prod_img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
